# Generated by Django 5.1.1 on 2024-09-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id_province', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text='Nom de la Province Ecclésiastique', max_length=100)),
                ('archeveque', models.CharField(blank=True, default='Inconnu', help_text="Nom de l'Archevêque Métropolitain de la Province Ecclésiatique", max_length=100)),
                ('description', models.TextField(help_text='Une courte description de cette Province Ecclésiatique')),
            ],
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation_gps', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('aumonier_diocesain', models.CharField(max_length=100)),
                ('eveque', models.CharField(max_length=100)),
                ('eveque_emerite', models.CharField(blank=True, max_length=100, null=True)),
                ('saint_patron', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dioceses', to='geographie.province')),
            ],
        ),
    ]
