# Generated by Django 5.1.1 on 2024-09-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0004_departement_diocese'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/dioceses/'),
        ),
    ]
