# Generated by Django 5.1.1 on 2024-10-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0006_alter_diocese_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='type',
            field=models.CharField(choices=[('suffragant', 'Suffragant'), ('archeveche', 'Archevêché')], default='suffragant', max_length=100),
        ),
    ]
