# Generated by Django 5.1.1 on 2024-10-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0007_diocese_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diocese',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.jpeg', null=True, upload_to='photos/dioceses/'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation_gps', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('aumonier_zonal', models.CharField(max_length=100)),
                ('vicaire_episcopal', models.CharField(max_length=100)),
                ('saint_patron', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, default='photos/default.jpeg', null=True, upload_to='photos/zones/')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='geographie.diocese')),
            ],
        ),
    ]
