# Generated by Django 5.1.1 on 2024-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0008_alter_diocese_photo_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='nom',
            field=models.CharField(help_text='Nom de la Province Ecclésiastique', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
