# Generated by Django 5.1.1 on 2024-10-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0009_alter_departement_nom_alter_diocese_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
