# Generated by Django 5.1.1 on 2024-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0010_diocese_slug_province_slug_zone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diocese',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
