# Generated by Django 5.1.1 on 2024-10-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0011_alter_diocese_slug_alter_province_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diocese',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='nom',
            field=models.CharField(blank=True, help_text='Nom de la Province Ecclésiastique', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
