# Generated by Django 5.1.1 on 2024-10-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0013_paroisse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paroisse',
        ),
    ]
